#include "python.h"

int transpile_python(struct arguments_t arguments)
{
    if (!arguments.specified_output_filepath)
    {
        arguments.output_filepath = "a.py";
    }
    FILE* file = fopen(arguments.filepath, "r");
    FILE* output_file = fopen(arguments.output_filepath, "w");
    if (fopen(arguments.filepath, "r") == NULL || fopen(arguments.output_filepath, "w") == NULL)
    {
        printf("brainfrick: A fatal error has occured. File does not exist when attempting transpilation read.\n");
        return -1;
    }
    
    if (arguments.infinite_cells) 
    {
        printf("brainfrick: A fatal error has occured. Unlimited Cells is not supported by transpiling.\n");
        return -1;
    }

    

    bool exit = false;
    char program;
    int loop_level = 0;

    // Initial code
    fputs("# Generated by brainfrick, a brainfuck utility\n", output_file);
    fputs("# https://github.com/tatewilhelm/brainfrick\n\n", output_file);

    fputs("import sys\n", output_file);
    fputs("cells = [0] * 30000\n", output_file);
    fputs("cell_ptr = 0\n", output_file);
    fputs("input_queue = []\n", output_file);
    
    while (!exit)
    {
        program = fgetc(file);

        for (int i = 0; i < loop_level; i++)
        {
            fputc('\t', output_file);
        }

        switch (program)
        {
        case '+':
            fputs("# +\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("if cells[cell_ptr] == 255:\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcells[cell_ptr] = 0\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("else:\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcells[cell_ptr] = cells[cell_ptr] + 1\n", output_file);
            break;
        case '-':
            fputs("# -\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("if cells[cell_ptr] == 0:\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcells[cell_ptr] = 255\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("else:\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcells[cell_ptr] = cells[cell_ptr] - 1\n", output_file);
            break;
        case '>':
            fputs("# >\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("if cell_ptr == len(cells):\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcell_ptr = 0\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("else:\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcell_ptr = cell_ptr + 1\n", output_file);
            break;
        case '<':
            fputs("# <\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("if cell_ptr == 0:\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcell_ptr = len(cells)\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("else:\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcell_ptr = cell_ptr - 1\n", output_file);
            break;
        case '.':
            fputs("# .\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("print(chr(cells[cell_ptr]), end = \"\")\n", output_file);
            break;
        case ',':
            fputs("# ,\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("if len(input_queue) == 0:\n", output_file);
            // If nothing in input queue
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tinp = input()\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tinp = inp + \'\\n\'\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\ti = 0\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\twhile i < len(inp):\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\t\tinput_queue.append(inp[i])\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\t\ti = i + 1\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcells[cell_ptr] = ord(input_queue.pop(0))\n", output_file);
            
            // If still characters in input queue
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("else:\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("\tcells[cell_ptr] = ord(input_queue.pop(0))\n", output_file);
            break;
        case '[':
            fputs("# [\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            fputs("while cells[cell_ptr] > 0:\n", output_file);
            loop_level++;
            break;
        case ']':
            fputs("# ]\n", output_file);
            for (int i = 0; i < loop_level; i++)
            {
                fputc('\t', output_file);
            }
            loop_level--;
            break;    
        case EOF:
            if (arguments.return_ending_cell)
            {
                fputs("sys.exit(cells[cell_ptr])\n", output_file);
            }
            exit = true;
            break;
        default:
            break;
        }
    }

    fclose(file);
    fclose(output_file);

}